import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-between flex-wrap bg-gray-700 p-4">
          <div className="flex items-center flex-shrink-0 text-white mr-6">
            <img src="/logo.png" width="36" height="36" alt="Perspective logo" />
          </div>

          <div className="flex-grow flex items-center w-auto text-white">Funnel Preview</div>
        </nav>

        {children}
      </body>
    </html>
  );
}
